source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

%w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
  gem lib, git: "https://github.com/rspec/#{lib}.git", branch: 'main'
end